In [3]:
import numpy as np
import pandas as pd
import openrouteservice

In [4]:

dist = np.array([[5, 9, 1, 3], 
                 [10, 4, 2, 2], 
                 [7, 8, 4, 5],
                [1, 3, 6, 9]])
from scipy.optimize import linear_sum_assignment
driver, pickup = linear_sum_assignment(dist)
pickup
dist[driver,pickup].sum()

11

In [ ]:
print(driver)

[0 1 2 3]


In [ ]:
print(pickup)

[2 1 3 0]


In [ ]:
df=pd.DataFrame(dist)

In [ ]:

# assignments = pd.DataFrame({
#     'worker': df.loc[row_ind].values,
#     'job': df.loc[col_ind].values,
#     'Original_to_Assigned_Distance_km': cost[row_ind, col_ind]
# })

assigned_values = dist[driver, pickup]
print(assigned_values)

[1 4 5 1]


In [ ]:
r=linear_sum_assignment(dist)
print(r)

(array([0, 1, 2, 3], dtype=int64), array([2, 1, 3, 0], dtype=int64))


In [ ]:
c=linear_sum_assignment(dist)[1]
print(c)

[2 1 3 0]


In [ ]:
cm=pd.read_csv('processed data.csv')
cm.head()

Bus Route number Institute  Driver_Lat  Driver_Lon     PP_Lat  \
0  KA53AC0634            1  Chanakya   12.958330   77.525384  12.958330   
1  KA53AC0540            2  Chanakya   13.249466   77.708713  13.249466   
2    KA439840            1     Gitam   13.017359   77.657409  13.010978   
3   KA43A0245            2     Gitam   13.033098   77.553878  12.967800   
4    KA439841            3     Gitam   13.099021   77.574234  13.034584   

      PP_Lon  Dead km  Dead_KM_Haversine  
0  77.525384      0.0           0.000000  
1  77.708713      0.0           0.000000  
2  77.695193      6.0           4.154431  
3  77.536097      6.0           7.512091  
4  77.557486      8.0           7.391135

In [ ]:
coordinates=pd.DataFrame()
coordinates['lon1']=cm['Driver_Lon']
coordinates['lat1']=cm['Driver_Lat']
coordinates['lon2']=cm['PP_Lon']
coordinates['lat2']=cm['PP_Lat']

In [ ]:
coordinates.head()

lon1       lat1       lon2       lat2
0  77.525384  12.958330  77.525384  12.958330
1  77.708713  13.249466  77.708713  13.249466
2  77.657409  13.017359  77.695193  13.010978
3  77.553878  13.033098  77.536097  12.967800
4  77.574234  13.099021  77.557486  13.034584

In [ ]:
cost_mat=pd.DataFrame(cm['Bus'])

In [ ]:
cost_mat.head()

Bus
0  KA53AC0634
1  KA53AC0540
2    KA439840
3   KA43A0245
4    KA439841

In [ ]:
cost_mat[cm['Bus']]=''


Bus KA53AC0634 KA53AC0540 KA439840 KA43A0245 KA439841 KA439842  \
0  KA53AC0634                                                              
1  KA53AC0540                                                              
2    KA439840                                                              
3   KA43A0245                                                              
4    KA439841                                                              

  KA53B6963 KA53AC0345 KA51B9664  ... KA07A2722 KA51B9235 KA53B1064 KA53D0153  \
0                                 ...                                           
1                                 ...                                           
2                                 ...                                           
3                                 ...                                           
4                                 ...                                           

  KA53B1072 KA53B0960 KA53B0958 KA53B0952 KA53B1075 KA53B1061  
0                                                              
1                                                              
2                                                              
3                                                              
4                                                              

[5 rows x 54 columns]

In [ ]:
print(coordinates.iloc[3:5])

        lon1       lat1       lon2       lat2
3  77.553878  13.033098  77.536097  12.967800
4  77.574234  13.099021  77.557486  13.034584


In [ ]:
lower_index=5
upper_index=10
batch=coordinates.iloc[lower_index:upper_index]
print(batch)

        lon1       lat1       lon2       lat2
5  77.657409  13.017359  77.630696  13.032014
6  77.574234  13.099021  77.592635  13.058063
7  77.484809  13.008149  77.550299  12.973794
8  77.536863  13.309392  77.443245  13.201514
9  77.692368  13.008776  77.692368  13.008776


In [2]:
import openrouteservice

# Initialize the client with your API key
api_key = "5b3ce3597851110001cf6248c01d29a9cb6644ada55104d3f6ad8d70"
orsmap = openrouteservice.Client(key=api_key)

In [ ]:
def get_road_distance(origin_lat, origin_lon, dest_lat, dest_lon):
    origin = f"{origin_lat},{origin_lon}"
    destination = f"{dest_lat},{dest_lon}"
    try:
        result = orsmap.directions(coordinates=[origin], profile='driving-car')
        distance = result['routes'][0]['summary']
        if distance['status'] == 'OK':
            return distance['distance']/ 1000  # meters to km
        else:
            return np.inf
    except:
        return np.inf  # API or network failure fallback


In [ ]:
r=1
c=40
cost_matrix = np.zeros((r,c))

print("Calculating distance matrix...")
for i in range(r):
    for j in range(c):
        dist = get_road_distance(
            drivers.loc[i, 'Driver_Lat'], drivers.loc[i, 'Driver_Lon'], #needs to be changed to long,lat when using osrm
            pickups.loc[j, 'PP_Lat'], pickups.loc[j, 'PP_Lon']
        )
        cost_matrix[i, j] = dist
        sleep(0.1)  

In [ ]:
print(route['routes'][0]['summary']['distance'])

4664.8


In [ ]:
dis=round(route['routes'][0]['summary']['distance']/1000, 3)
print(f'Route Distance: {dis} km')
# c_m=dist
# c_m.head()

Route Distance: 4.665 km


In [ ]:
# c_m.to_excel('sample distances matrix.xlsx', index=False)

In [ ]:
API_KEY = '5b3ce3597851110001cf6248c01d29a9cb6644ada55104d3f6ad8d70'
gmaps = googlemaps.Client(key=API_KEY)

In [ ]:
result = gmaps.distance_matrix(
    origins=['13.0173592,77.65740947'], 
    destinations=['13.01097849,77.69519276'], 
    mode='driving')

In [ ]:
distance_m = result['rows'][0]['elements'][0]['distance']['value']  
distance_km = distance_m / 1000